name: behave
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Run Buildx
        run: |
          docker buildx build . \
            --load \
            --progress=plain \
            --tag secret-magpie \
            --platform linux/amd64
      - name: Install and run behave
        run: |
          docker run \
            -e SKIP_IN_RUNNER="" \
            -e SECRETMAGPIE_GITHUB_PAT=${{ secrets.SECRETMAGPIE_GITHUB_PAT }} \
            -e SECRETMAGPIE_ADO_PAT=${{ secrets.SECRETMAGPIE_ADO_PAT }} \
            -e SECRETMAGPIE_GITLAB_CE_PAT=${{ secrets.SECRETMAGPIE_GITLAB_CE_PAT }} \
            -e SECRETMAGPIE_GITLAB_PAT=${{ secrets.SECRETMAGPIE_GITLAB_PAT }} \
            --entrypoint sh \
            secret-magpie \
            -c "pip install behave; python -m behave"
